# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45efc34e4bfd9c02a879664ba83bc96397d20c4dc045913b0cd5cb9ed8007cec0ad6b4c2eb48caf91d0132bf6efce4653c1b8758a148ce043532173c14f48abf

test:
  secret_key_base: ac8d0e4828052a33ef691dd7c75e9e44f1fcd092f44a4f70351c828b110b7997eeece4506ce90d1f72e7f251f9c38aea285da80ba66246d2051ad3a8221c37ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
